version: "3.9"

x-logging:
  &highlight-logging
    driver: fluentd
    options:
        fluentd-address: "otel.highlight.io:24224"
        fluentd-async: "true"
        fluentd-sub-second-precision: "true"
        tag: "highlight.project_id=ng2l3rd1"

services:
  server: 
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes: 
    # Development
    # - ./images:/app/images
    # Prod
      - ~/data/galere/images:/app/images
    # This is for testing purposes
    # TODO: Remove before deploying.
    # ports:
    #   - 3000:3000
    depends_on:
      - db
    logging: *highlight-logging
  
  caddy:
    image: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
      # - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    logging: *highlight-logging 

  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata 
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
    volumes:
      - ~/data/galere/psql:/var/lib/postgresql/data/pgdata 
    logging: *highlight-logging 
